AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: My SAM Application

Resources:
  MyDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: MyTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: MyFunction
      Handler: app.lambda_handler
      Runtime: python3.9
     
      Environment:
        Variables:
          TABLE_NAME: !Ref MyDynamoDBTable
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  MyApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
     StageName: prod
     DefinitionBody: 
      swagger: '2.0'
      info:
        title: 'My API Gateway'
        version: '1.0'
      paths:
        /hello:
          get:
            x-amazon-apigateway-integration:
              uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction.Arn}/invocations
              httpMethod: POST
              type: aws_proxy